name: whole pipeline to push image to registry
on: [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: smikesword/config-service
  VERSION: latest


jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: SAST scan with Grype
        uses: anchore/scan-action@v7
        id: scan
        with:
          path: "${{ github.workspace }}"  # path to the checked-out repository
          fail-build: false
          severity-cutoff: high

      - name: upload vulnerability scan
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper which requires passing tests
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: package, scan and publish
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Build container image using cloud native buildpack
        run: |
            chmod +x gradlew
            ./gradlew bootBuildImage \
              --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: OCI image vulnerability scanning
        uses: anchore/scan-action@v7
        id: image_scan
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
          output-format: sarif

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.image_scan.outputs.sarif }}

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}